### ISSUE TITLE
[editor] 削除ボタンを作る

### ISSUE THREAD

**Issue by mpses** [OrientationCommittee/OC24visitor-editor#18]
編集ボタンがあってもいいかも

**Comment by micchat** [comment]
これ、記事一覧ページに削除ボタン作ると誤削除とか増えない...？
編集ページに削除ボタンのほうが良いんじゃないかと考えたんだけど、どうでしょう？（使い方の想定が違ったらごめんね） @mpses

**Comment by micchat** [comment]
表示/非表示も実際の切り替えは編集ページで行わせて、一覧ページでは非表示のものを一覧するか選択するボタンとかにするのはどうですか...！

**Comment by mpses** [comment]
マジでその通り過ぎる！！両方ともそうしよう

________________________________

飼沼 隼 (Shun Kainuma)
