### ISSUE TITLE
GET & `[title]/edit` では初期値を取ってきた値にする（`/new` ではまっさらの状態のまま）

### ISSUE THREAD

**Issue by mpses** [OrientationCommittee/OC24visitor-editor#29]
API ができてから（#25）でOK

`[title]/edit` においては、`/` からの遷移時に記事IDを渡して、記事IDをAPIにぶん投げることにより単一記事の情報を取得する。それをエディタおよび`HtmlToolbar`の初期値にする。

import ボタンは最終的には廃止

**Comment by micchat** [comment]
@mpses 記事IDの渡し方、クエリパラメータっての使えば大丈夫そう？

**Comment by micchat** [comment]
urlからmongoのidが見れちゃうことに問題がある？？

**Comment by mpses** [comment]
今取り込んでてちょっとちゃんと考えられないんだけど、props使うだけじゃ無理かな（ページ移動あるからむりか？）
一応パラメータは隠せるよ https://zenn.dev/pk_yakkun/articles/39dbcac61d569b

**Comment by mpses** [comment]
URLは[title]/editだけにしてほしいかなできれば

**Comment by micchat** [comment]
ありがとうー
教えてもらった記事の通りやってみた＆色々調べたけど、記事のやり方のuseRouterは廃止されてて、代わりにuseSearchParamsを使うっぽい、けど、Linkコンポーネントでasを使ってqueryを隠してしまうと、useSearchParamsではqueryが取得できない（nullになる）ってところです。
完全に詰まってます。

**Comment by mpses** [comment]
アップデートでそんなことになってたのか、、props使うのは無理となるとどうすればいいかね、、別にIDってバレても困らない気もするけどどうなんだろう @HornCake h

**Comment by mpses** [comment]
@.keyhr に助けを乞うという選択もあります（）

**Comment by micchat** [comment]
id隠したいのってどういう意図？
（というか、[id]/editじゃだめ？titleっていう一意じゃないものをURLにしないほうが良いのかな、と思い始めた）

**Comment by HornCake** [comment]
Basic認証した先でのシステムだからidでもいい気はするけど、そのidがデータベースで使われてるidだから他ではあまり使いたくないよねぇ

**Comment by micchat** [comment]
そうなのか..._idとは別にidフィールド作るのは？コスト高い？

**Comment by HornCake** [comment]
それするくらいなら[id]/editでいいとはおもう
そこまでする必要はないかなぁ

**Comment by micchat** [comment]
ぬあー、どうしましょう

**Comment by HornCake** [comment]
ちなみにvisitorではパスのわかりやすさのために/24/visitor/[title]になってる
まあこっちは公開する前提だから土俵が違うけど

**Comment by micchat** [comment]
あ、じゃあ一応titleは一意と考えてるってことで良き？

**Comment by micchat** [comment]
titleから記事を引っ張ってくる機能があれば解決？

**Comment by HornCake** [comment]
うん

**Comment by micchat** [comment]
おけ
ちなみに、titleから記事を引っ張ってくるってAPIのほうで用意できたりする？
editページでもう一回getArticles()するのあんまりスマートじゃない気がする

**Comment by HornCake** [comment]
僕の想定では
1. 記事一覧画面で記事全データとってくる
2. その段階でタイトルとid紐付けておく
3. 記事全データから選んだ記事データを渡して記事編集ページいって編集する
4. 保存時、編集前のデータからタイトルとid紐付けてdb更新する

だった

**Comment by HornCake** [comment]
ページ遷移時にpropsみたいにデータ渡せないんだね？
もしくはapp全体で共通のデータ保持しとくとかも←これはデータ更新の機会が減るから良くないんだった

**Comment by micchat** [comment]
いやー、技術的に本当に出来ないかどうかは僕にはわからないな。

**Comment by HornCake** [comment]
ほんじゃあタイトルから検索できるの作っとくわ

**Comment by micchat** [comment]
記事のデータをそのまま全部query paramsにしちゃう？ArticleTypeの全フィールドをqueryで渡す？

**Comment by micchat** [comment]
作ってもらえたらだいぶ助かる。あと、タイトルの一意性はどうやって保証しよう？

**Comment by micchat** [comment]
タイトルのリストを取り出せるような機能が有れば/editでの保存時にvalidateしてから送信できる？

**Comment by HornCake** [comment]
同一タイトルは保存不可にしてもらおうかな
全タイトル取得のutilも作っとくわ

**Comment by micchat** [comment]
りょーかい、ありがとー

**Comment by micchat** [comment]
ごめんこれ、タイトル重複を防ぐ機能付け忘れてた。
ちなみに、apiに重複タイトルで送った場合って上書きされちゃう？それとも単に防がれる？

**Comment by HornCake** [comment]
エラー出るな

**Comment by mpses** [comment]
issue 立てとく
