### ISSUE TITLE
新規記事を保存後、backして一覧画面に飛ぶと、リロードし直さないと保存した記事が出てこない

### ISSUE THREAD

**Issue by micchat** [OrientationCommittee/OC24visitor-editor#43]
@HornCake お疲れ様！これって直せるやつ？？

**Comment by HornCake** [comment]
対応するわ
おそらくページ遷移時に**クライアントサイド**でリロード処理をすればいいはず

**Comment by HornCake** [comment]
直した
ルートのpage(server side)直下にArticleListsというClient Side Componentを作って、それのマウント時にリフレッシュしてる
ホームのページを直したいことがあったらcomponents/ArticleLists.tsxを編集してもらえれば

**Comment by micchat** [comment]
ありがとうございます...

**Comment by micchat** [comment]
仕事早すぎてびっくりΣ(ﾟдﾟ|||)
感謝！！
