### ISSUE TITLE
[editor] タイトル重複を防ぐ

### ISSUE THREAD

**Issue by mpses** [OrientationCommittee/OC24visitor-editor#51]

**Comment by micchat** [comment]
<img width="1470" alt="Screenshot 2024-01-07 at 23 06 08" src="https://github.com/OrientationCommittee/OC24visitor-editor/assets/134117798/7da43287-8574-40ea-b571-b54cea7ee662">
こんな感じで実装しようとしたんだけど、async,await使えないみたい、どうやったら実装できる？ @mpses

**Comment by mpses** [comment]
これLexicalの仕様的に仕方ないよね？諦めて開いた時のデータにするか、それかLexical使わずに単純に送信時にエラー吐かせるか

**Comment by mpses** [comment]
フォームのバリデーションとしてじゃなくて，APIにデータ送る時にエラー吐かせてダイアログに出すってこと

**Comment by micchat** [comment]
Lexicalの問題なのかなぁ...わかんない

**Comment by micchat** [comment]
↑これ、なんか今試したら動いてる。hot reloadが悪さしてた説はあるかもしれない。一旦branch切って上げておくから、何らかの方法で他の環境で試してみてほしい @mpses @HornCake

**Comment by micchat** [comment]
これ上手く行ってない

**Comment by micchat** [comment]
どしたら良いんだこれ...現状だと、
/edit→タイトル変更なし　◯
/edit→タイトル変更あり1回目　◯
/edit→タイトル変更あり2回目以降　✗
/new→タイトル追加　◯
/new→タイトル追加の後変更　✗
最後に関しては、/newの更新後にlocation.href="/"するようにしちゃえばとりあえず問題なさそうだけど、/editでの複数回更新は多分できるようにしないとだよね。 @mpses @HornCake 
どうしたらできるようになるかわからないです。助けてください〜

**Comment by HornCake** [comment]
initialTitleをcurrentTitleとuseStateして、保存のたびに更新するんじゃダメかな

**Comment by HornCake** [comment]
あーuseStateはclient sideじゃないからuse client にすべきかな
