### ISSUE TITLE
[editor] スタイルをvisitorに揃える

### ISSUE THREAD

**Issue by micchat** [OrientationCommittee/OC24visitor-editor#55]
現在のvisitorのデザインって確定版ですか？ @mpses

**Comment by mpses** [comment]
いや，まだ変えようと思ってる

**Comment by mpses** [comment]
完成したらお伝えします！ @23micchan

**Comment by mpses** [comment]
@23micchan ごめん一旦そんな変えないことになったから、やってもらえるかな？Adobe Fonts 導入してるから（nextのやり方は調べれば出てくる）、typekit project id を visitor の .env と同じのでやればできるはず！

**Comment by micchat** [comment]
fot-tsukuardgothic-std、ページ全体で読み込んで良いの？それとも、Editor内部だけ？ @mpses

**Comment by micchat** [comment]
contenteditableだけに適用する？

**Comment by mpses** [comment]
UIはデフォルトフォントでいいかな（どうでもいい話：Winでの表示を考えたらHiraginoにしたいけど、委員会内のページなのでまじでどうでもいい）
だからcontenteditableだけでお願い！
