### ISSUE TITLE
[editor]保存成功をユーザーにわかりやすく伝える

### ISSUE THREAD

**Issue by micchat** [OrientationCommittee/OC24visitor-editor#56]
dbへの通信終了をユーザーに伝える機能があったほうが良いかなと。一定時間で消えるトースト通知を実現するためのContextは、ローカルで実現できることを確認したので、もしその方向性で良ければそれで進めたいです。

**Comment by HornCake** [comment]
ありよりのあり
トースト通知じゃなくてもローディング記号とかでもいいかも？

**Comment by micchat** [comment]
ちな、通信中に「Loading...」画面を表示する処理自体は現状でも入れてるつもりなんだけど、たぶん処理が短すぎて表示されてない？（要検証）みたいで、それなら、成功したよっていうのを伝える形のほうが良いかなって思ってる。
具体的には、Editor.tsxで定義されてるsetLoading関数をpropsとして、HtmlToolbarPluginに渡して、通信開始時にsetLoading(true);処理終了時にsetLoading(false);を挟んでる。

**Comment by HornCake** [comment]
んー一応Loading画面の意図はその間絶対にボタンとか触らせないためだから極力ロード中は編集画面を見せない方がいい気はする
Load中に全ボタンの処理を行わないようにしてもいいけどそれだとめんどいかなぁと思ったんだけどどうかな？

**Comment by micchat** [comment]
loading画面の意図なるほどね、ありがとう。
ただ、/edit画面でexportボタン押したときのloadingがなんか表示されてない気がするんだよね。
もし、これが昨日言った通り「短すぎる」故に表示されてないならユーザーへの別の通知手段を重ねがけする必要がありそうだから、loading画面がsetLoadingでちゃんと入っているのか確認をお願いしたい（どうしたら確認できるかわからなくて...）
このsetLoadingが機能して無くてloading画面が表示されてないだけだったらそれを直せばトーストとかはいらない感じ。

**Comment by micchat** [comment]
toastの意図としては、Loading中の処理を変えるってことではなくて、Loading後に編集画面が表示された際に通知を入れたいってこと！上手く伝えられなくてごめん〜
loading画面が一定時間入っていれば（/edit最初の読み込み時みたいに）わかりやすいんだけどね。

**Comment by HornCake** [comment]
```
try {
  setLoading(true);
  // ここでthenを使う
  updateArticle(article._id, article).then(() => {
    setLoading(false);
  });
} catch (e) {
  console.log(e);
}
```
updateArticleは非同期処理だから書き方的にはこれが正しいかな
といってもここでは非同期処理が終わるまでの間に操作していいところだから、画面全体を無効化するLoading入らないかも
むしろtoastでただ通知するだけでいい気がする
toastでやるならこの上のコードのsetLoadingをtoast用のやつに変えればいいかな

**Comment by micchat** [comment]
うむむむ...ありがとう！！
promise無視してたから、loading画面が表示されなかったのかな...？
通知組み込んで見るので、できたらまた確認頼みます！（急がないので、時間のある時で大丈夫）
