### ISSUE TITLE
[editor] toolbox の一行目のロゴが右にズレてる

### ISSUE THREAD

**Issue by mpses** [OrientationCommittee/OC24visitor-editor#7]

**Comment by micchat** [comment]
これ、padding-left:8px;いれないと、react-iconsのHeadingアイコンが左に寄ってtoolbarとinlineToolbarでボタンがズレてるように見えるからこんな感じに一旦したんだけど、どう直すのが良い？ @mpses

**Comment by mpses** [comment]
見た目的に（＝意図しない挙動ではなくて）ロゴ同士がズレてるように見えるってこと？それならボタン同士の間隔を結構取ればあんまり気にならないかな？[`gap-2`](https://tailwindcss.com/docs/gap)(`gap: 8px;`)とか @23micchan

**Comment by mpses** [comment]
あとボタン 40px に対する svg のサイズも 24px ぐらいに下げると綺麗な気がする

**Comment by micchat** [comment]
そう。paddingつけないとHとBがずれちゃうんだよね。
一旦、padding戻して、svgを24pxに下げてみた。
<img width="722" alt="Screenshot 2024-01-01 at 21 12 26" src="https://github.com/OrientationCommittee/OC24visitor-editor/assets/134117798/f255bc6c-3de4-4c9d-8125-26233f54953b">
眺めてたらあんまり気にならなくなってきてしまったので、これで良さそうならこれで！
