### ISSUE TITLE
[editor] 一覧画面でshownステータスがわかるようにしたい＆リンク反応範囲をカードいっぱいに広げたい

### ISSUE THREAD

**Issue by micchat** [OrientationCommittee/OC24visitor-editor#73]
と思うんだけどどうですか？ @mpses

**Comment by mpses** [comment]
賛成

対応できる？
________________________________

飼沼 隼 (Shun Kainuma)

**Comment by micchat** [comment]
するよー。けど、shownの表示どんな感じでやったら良い？デザイン自信なくて...指針もらえたら作ってみます！

**Comment by micchat** [comment]
単に背景色変えるとかでもok？

**Comment by micchat** [comment]
あと、dbへの通信を使ったローカルでのテストってもう出来ない？？変更しちゃだめだよねこれ...

**Comment by mpses** [comment]
デザインは例えばカードの右上とかに
・表示
もしくは
・非表示
っていう感じのを作って・の色を（非表示：黒）と（表示：緑）で分けるのはどう？

**Comment by mpses** [comment]
dbは鬼頭がこれからテスト版のを作ってくれそう

**Comment by micchat** [comment]
あああ、ごめんね、やります。

**Comment by mpses** [comment]
急かしてるみたいになってるけど俺が見てすぐわかるように issue assign
しとこと思っただけでマジで違うごめん！委員会内のツールだしゆっくりで大丈夫だよ！

2024年1月17日(水) 14:11 23micchan ***@***.***>:

**Comment by micchat** [comment]
あ！こっちこそごめん！言い方めっちゃ深刻みたいになってた〜
割と忘れかけてたから、気づかせてくれて助かったよ！
プルリク出したので時間あるときに確認お願いします！！
